### PR TITLE
updated the (html and css) of "ingredient box" of the recipe page

### PR DESCRIPTION
**Pull request by ctyuucsdedu**

### CODE REVIEW

**Comment by ctyuucsdedu** [comment]
Simply made pull request from main and front-end to my branch, then push my changes of the recipe page to my branch, and now trying to merge my branch into the front-end branch. Thank you.

**Comment by ctyuucsdedu** [comment]
Also, I have left comments in the html file with  where they all require js to insert the data or the actions from js.

**Review by TuckerFrandsen — CHANGES_REQUESTED** [review]
Hey Kevin, could you make sure that the HTML validation passes on this pull request? There seems to be a few minor issues that need fixing before we merge this into the front end branch.

**Comment by ctyuucsdedu** [comment]
Hi Tucker, the html could not be satisfied since it is not completed yet. I could fix other minor issues but it won't change too much (such as adding alt to input..). It is ok to just merge pull request and fix the issues later since some of them require js to accomplish. Thank you.

**Comment by Steven-Christensen** [comment]
gonna take a look at it from your personal branch rn

**Review by mlgi — CHANGES_REQUESTED** [review]
HI kevin,

Your branch is extremely out of date, please merge front-end into your branch to get the new changes. This involves the changes we made to the deployment scripts. 

You can merge this into front-end afterwards, then we can get started on porting over your CSS in the existing ingredients component.

**Comment by ctyuucsdedu** [comment]
ok

**Pull request closed without merging**
