### PR TITLE
New theme changes with Css

### PR DESCRIPTION
**Pull request by dmcgrath19**
Adjust colour display, change font, add smoothing borders. The idea is that it begins to look coherent in the sense of aligning with our initial goals in Miroboard and has the comforting user feel. For example, instead of the text being "loud" it now caries that same urban feel as well as altering some of the images to make our app feel seamless as well.

### CODE REVIEW

**Review by TuckerFrandsen — APPROVED** [review]
Good improvements to the css.

**Review by mlgi — APPROVED** [review]
This is beautiful, times new roman is *canceled*.

**Review by ctyuucsdedu — APPROVED** [review]
Impressive!!

**Comment by TuckerFrandsen** [comment]
Merging this PR since the tests are currently failing due to problems we are aware of and are working to fix.

**Pull request merged**
