### PR TITLE
Eslint

### PR DESCRIPTION
**Pull request by ArturoAmaya**

### CODE REVIEW

**Comment by ArturoAmaya** [comment]
Alright! This is a quick fix to add ESLint to VSCode, so that errors are easier and quicker to catch locally. 
To get this working, you should run:
`npm install eslint`
on vscode or your terminal (for windows people without wsl *gasp*)
Then install this extension:
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

If you want to test it for yourself before merging to main, copy the edits to the relevant files on a local branch. 

here's some sample code that should give some errors so you can see it:

const helloYou    = (name)=> {
  name = 'you' || name   ;
  console.log("hello" + name + "!" )
}

**Comment by ArturoAmaya** [comment]
There is also a way to run a quick-fix, sort of like prettier's on save fixes. When you have code on vscode, click CTRL + SHIFT + P and look for "fix" to find a command called ESLint: Auto-fix all fixable problems" or something along those lines. click it, and it should fix everything it can about your code. All errors that remain are underlined in red. Hovering over them will explain what they are and what rule is being broken. 

We now use Google's linting configuration, except I override the single-quotes setting and something about line endings (if you're interested, it was this: https://eslint.org/docs/rules/linebreak-style)

**Review by TuckerFrandsen — APPROVED** [review]
Absolutely great work! I love it. This should definitely help improve linting and enforcing a common code style.

**Review by sschaeff2023 — APPROVED** [review]
Looks awesome, ready to merge to main

**Pull request merged**
