### PR TITLE
updated ingredients box

### PR DESCRIPTION
**Pull request by ctyuucsdedu**

### CODE REVIEW

**Comment by ctyuucsdedu** [comment]
change

**Comment by ctyuucsdedu** [comment]
I made a pull request from front to mine.

**Comment by Steven-Christensen** [comment]
Kevin I think there are some HTML things to change before we can merge your branch to front end. You don't need a review to merge front-end to your branch. I'm not sure if you thought you did or not.

**Review by mlgi — APPROVED** [review]
The discrepancies outside of recipe_page.css and recipe_page.html were because kevin's branch was branch from a more recent verision of `main` unlike the `front-end` branch which was behind main. I made sure to look over each file to and compare them with the deployment team's scripts so that it doesn't break anything.

Your HTML files aren't passing the tests but that's alright for now. The `IngredientsInfo.js`  component will be what you worked on #125 . Now we just need to port your CSS over.

**Comment by ctyuucsdedu** [comment]
So may I make the merge pull request?

**Comment by mlgi** [comment]
I got it, thank you kevin o7

**Comment by ctyuucsdedu** [comment]
Ok, I am going to work on other classes now. Please tell me if I did something incorrectly so I could change them. Thank you

**Pull request merged**
